version: "3.9"
   
services:
  db:
    image: postgres
    container_name: db
    volumes:
      - /VAR/LIB/POSTGRESQL/DATA:/custom/mount
    environment:
      - POSTGRES_DB=testing
      - POSTGRES_USER=testing
      - POSTGRES_PASSWORD=password
  web:
    build: .
    container_name: web
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - DATABASE_URL=postgres://testing:password@localhost:5432/testing
    depends_on:
      - db

