version: "3.9"
   
services:
  db:
    image: postgres
    container_name: db
    ports:
      - "5432:5432"
    volumes:
      - /VAR/LIB/POSTGRESQL/DATA:/custom/mount
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
  web:
    build: .
    container_name: web
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - DATABASE_URL=postgres://postgres:password@db/postgres
    depends_on:
      - db

